= Sites
:toc: right
:imagesdir: images

Sites add support for building building pages, in addition to form-based content.

NOTE: For a hands on introduction to sites and the concepts described here, visit the https://developer.enonic.com/docs/my-first-site[My first site tutorial].

== Introduction

Sites unlock powerful functionality for managing websites and creating visually oriented content like <<pages#, pages>>, <<page-templates#,page templates>> and <<pages/fragments#, fragments>>.

Similar to content projects, you may add applications to a site. For sites however, purpose-specific applications like sitemap.xml, robots.txt, Google Analytics, SEO Metafields, and Siteimprove introduce features and management capabilities beyond that of basic content.

== Usage

Site content serves the purpose of acting as website's root entry. It enables selecting and configuring applications for a website. Content types, components, filters, x-data and more from the applications selected will be available for use inside the site content tree based on the site configuration.

Sites can be created anywhere in your content structure, but they are commonly created as a child of the root content.


== Defition (portal:site)

The site content type is built-in. It is a subtype of `base:structured`, and has the following definition:

super-type:: base:structured
is-abstract:: false
is-final:: true
allow-child-content:: true


== The site engine

TODO: Point to Enonic App developer


When rendering sites and pages with the Enonic framework, request handling and resolving is performed by the <<../runtime/engines/site-engine#, site engine>>. It offers site-specific capabilities and request handling such as:

* Access control (based on content permissions)
* Controller resolving (via page or mappings)
* <<pages#, Component rendering>> (directly or via placeholders)
* <<../framework/contributions#, Page contributions>>
* <<../framework/processors#, Response processors>>


[#site_xml]
== site.xml

Applications declare support for sites by including the site.xml descriptor file.

This descriptor serves multiple purposes:

* Declares that this app supports sites (and CMS projects)
* Defines a form that lets you configure the application on a per site (or project) basis
* Define <<x-data#,X-data>> mappings
* Define controller and filter <<../framework/mappings#, mappings>>.
* Define <<../framework/processors#, response processors>>.

The descriptor must be placed in your app as: `src/main/resources/site/site.yaml`

.Minimal site.yaml example
[source,yaml]
----
kind: "Site"
form: []
----


.Site.yaml with all options in use
[source,yaml]
----
kind: "Site"
form:  # <1>
  - type: "TextLine"
    name: "company"
    label: "Company"
    occurrences:
      min: 1
      max: 1
  - mixin: "address"
xdata:  # <2>
  - name: "seo-settings"
mappings:  # <3>
  - controller: "/site/foobar/api.js"
    order: 10
    pattern: "/api/v\\d+/.*"
  - controller: "/site/pages/default/default.js"
    match: "type:'portal:fragment'"
processors:
  - name: "tracker"  # <4> <5>
    order: 10
----

<1> Define a <<schemas#forms,form>> for this app. The form is used to create site specific configuration for the app.
<2> Specify <<x-data#, X-data>> fields to use within the site scope.
<3> Controller and filter <<../framework/mappings#,mappings>> definitions
<4> Commonly used to add <<../framework/contributions#,page contributions>> to the response
<5> The order is used to decide execution order if multiple applications and processors are added to a single site.
