= Form Fragments
:toc: right
:imagesdir: images

Reuseable form definitions

== Introduction
If you find yourself in need of repeating the exact same form pattern across different schemas, form fragments may be what you're looking for. 

This is a special kind of schema, containging only a single <form#, form>. By referencing a form fragment from another schema, you pull the fragment form definition into the referencing schema's form.

== Usage

TODO
Like other schemas, Form fragments are defined in YAML. `site/mixins/[name]/[name].xml`. I.e. `src/main/resources/site/mixins/address/address.xml`.

.Sample form fragment
[source,xml]
----
<mixin>
  <display-name>Full address</display-name>
  <form>
    <input type="TextLine" name="addressLine">
      <label>Street address</label>
      <occurrences minimum="0" maximum="2"/>
    </input>
    <input type="TextLine" name="city">
      <label>City</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
    <input type="TextLine" name="zipCode">
      <label>Zip code</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
    <input type="TextLine" name="country">
      <label>Country</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
  </form>
</mixin>
----

Below is an example of a simple content type that references the address mixin above.

The mixin fields will simply be merged into the content type schema. 

[source,xml]
----
<content-type>
  <display-name>Using mixins</display-name>
  <form>
    <input type="TextLine" name="firstName">
      <label>First Name</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
    <input type="TextLine" name="lastName">
      <label>Last Name</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
    <mixin name="address"/>
  </form>
</content-type>
----

== Limitations

Form fragments are only supported for content schemas, and may not be used in other schema contexts such as identity providers and tasks.
