= Content Types
:imagesdir: ../images
:toc: right
:y: icon:check[role="green"]
:n: icon:times[role="red"]

Content types is the foundational schema type in Enonic XP. All content items must be based on a content type. Content types are used to define the sturcture and capabilities of a content items.

== Name
Every content type has a unique identifier in the following format `<namespace>:<name>`. Content types are either built-in, or custom defined by developers. 

== Built-in types

In addition to the custom defined types, several <<built-in>> content types exits. These use reserved namespaces such as `base`, `media` and `portal`, and are available for use in your content model. Built-in content types are typically used as super-types for custom content types, but can also be used directly when creating content items.

== Usage

Content types schemas are defined via YAML definitions. Below is an example content type definition:

[source,xml]
----
<content-type>
  <display-name>Person</display-name>  // <1>
  <display-name-label>Full Name</display-name-label> // <2>
  <description>Create a new person</description>  // <3>
  <super-type>base:structured</super-type>  // <4>
  <is-abstract>false</is-abstract>  // <5>
  <is-final>true</is-final>  // <6>
  <is-built-in>false</is-built-in>   // <7>
  <allow-child-content>true</allow-child-content>  // <8>
  <allow-child-content-type>base:folder</allow-child-content-type>  // <9>
  <allow-child-content-type>${app}:article-*</allow-child-content-type>
  <form/> // <10>
</content-type>
----

<1> *display-name* (required) The human readable name of the content type.
Optionally specify the <<../api/lib-i18n.adoc#,i18n>> attribute to define a mapping to localize the value.
The localization key must then be declared and localised in the resource bundle.
<2> *display-name-label* (optional; _since v7.1_) Enables you to override the default <Display Name> placeholder used in the content form.
<3> *description* (optional) Set a description that is shown when creating the content type.
<4> *super-type* (required) Refers to the root controller of the form. For custom content types this should typically be set to `base:structured`.
<5> *is-abstract* (optional; default: false) If true, you cannot create content with this content type.
<6> *is-final* (optional; default: false) If true, it is not possible to create new content types that “extend” this.
<7> *is-built-in* (optional; default: false) Only specified by built-in content types.
<8> *allow-child-content* (optional; default: true) If false, no content will be allowed to be created or moved under content of this content type
(e.g. prevents child content under media)
<9> *allow-child-content-type* (optional) If specified, only content of content types matching specified criteria will be allowed to be created or moved under content of this content type. The pattern matching used is the same as the one described in <<./schemas/input-types/contentselector#allowContentType, MATCH>>. image:xp-770.svg[XP 7.7.0,opts=inline]
<10> *form* (required) The custom <<schemas#forms,Form>> definition for your content type.

NOTE: `allow-child-content-type` will not have effect if `allow-child-content` is set to `false`


== Extend with mixins

You may dynamically extend both built-in and custom-defined content types through the use of <<mixins.adoc#,Mixins>>.