= CMS Fundamentals - Schemas, Content and Modeling
:imagesdir: schemas/images
:toc: right
:y: icon:check[role="green"]
:n: icon:times[role="red"]

This documentation covers the core concepts and features which make up Enonic's core CMS capabilities.

== Introduction

Enonic's CMS is built on top of the Enonic XP platform core. The heart of the CMS is a declarative schema system and a unified API to access all of your content. Content models are automatically reflected in the API, as well as Content Studio, along with full server-side validation, indexing and querying capabilities.

TODO: Quickstart, Developer 101

== The CMS stack

The CMS is composed from serveral independent software components, each documented separately. When put together, they make out Enonic's CMS stack. This is possible thanks to Enonic XP's modular architecture, and allows for unprecedented flexibility and adaptability - including the ability to build your own APIs and editorial interfaces should you need to. 

* https://developer.enonic.com/docs/ai[AI features] - Optional extensions for subscription customers.
* https://developer.enonic.com/docs/content-studio[Content Studio+] - Optional extensions for subscribing customers.
* https://developer.enonic.com/docs/content-studio[Content Studio] - Extensible authoring 
* https://developer.enonic.com/docs/intro[Headless API] - Available on Enonic Market
interface available on Enonic Market
* <<schemas#, Schema system>> - Define content types and content structures.
* https://developer.enonic.com/docs/xp[Enonic XP] - Core Platform including Storage, IAM and more.

More applications, such as SEO tools, Google Analytics and more, are available on Enonic Market.

== Main features

*Schema as code:* Flexible content modelling. +
*Hierarchies:* Organize content in a tree structure. +
*Media:* Image processing and delivery. +
*Versioning:* Version control and branching for content. +
*Workflows:* Define custom content lifecycles and   approval processes. +
*Layering:* For multi-language and multi-region use-cases. +
*Scalable:* Scale from small projects to global multi-brand deployments +
*Customizable:* Augment the platform, APIs and tooling through custom development.

Being built on top of Enonic XP, developers may adapt the platform, APIs and tooling extensively via Enonic apps, making it a versatile choice for organizations looking to manage their digital content in a way that is optimized for their needs.


