= Enonic CMS - Universal Content Management System
:toc: right
:imagesdir: images

Bend-over-backwards flexible platform CMS built on top of Enonic XP. Structure and manage content at any scale, and deliver it to any channel through a unified API.

== Introduction

Enonic CMS is an api-first, open source content management system built on top of Enonic XP. 

At its heart lies a declarative schema system and a unified API to access all of your content. Content models are automatically reflected in Content Studio and the API, along with full server-side validation, indexing and querying capabilities.

TODO: Quickstart, Developer 101

== Main features

Enonic CMS is used by organizations around the world to manage their content and digital assets.

*Schema as code:* Flexible content modelling. +
*Hierarchies:* Organize content in a tree structure. +
*Media:* Image processing and delivery. +
*Versioning:* Version control and branching for content. +
*Workflows:* Define custom content lifecycles and   approval processes. +
*Layering:* For multi-language and multi-region use-cases. +
*Scalable:* Scale from small projects to global multi-brand deployments +
*Customizable:* Augment the platform, APIs and tooling through custom development.

Being built on top of Enonic XP, developers may adapt the platform, APIs and tooling extensively via Enonic apps, making it a versatile choice for organizations looking to manage their digital content in a way that is optimized for their needs.


== The stack

Enonic CMS is composed from the following:

* https://developer.enonic.com/docs/xp[Enonic XP] - Platform including AIM, NoSQL storage and more.
* <<schemas#, Schema system>> - Define content types and content structures.
* https://developer.enonic.com/docs/intro[Headless API] - Available on Enonic Market
* https://developer.enonic.com/docs/content-studio[Content Studio] - Extensible authoring interface available on Enonic Market
* https://developer.enonic.com/docs/content-studio[Content Studio+] - Optional extensions for subscribing customers.
* https://developer.enonic.com/docs/ai[AI features] - Optional extensions for subscription customers.

More applications, such as SEO tools, Google Analytics and more, are available on Enonic Market.
