= Mixins
:toc: right
:imagesdir: images

Define a set of fields to be shared across content types.

== Introduction

Horizontal inheritance is a programming concept where fields can be reused across different objects. Mixins make it possible to dynamically extend existing existing content types with additional fields.

A Mixin may be added to all, or a specified list of content types. For instance, the SEO Meta fields application makes use of this, so editors may fine-tune SEO settings across all different content they produce. Also, Mixins may be explicitly enabled or made optional, so the editors may ensable or disable the mixin on a per content item basis.

In Content Studio, mixins are visualized as a separate tabs in the content editor.

== Usage

The file with mixin schema must be placed in the folder `cms/mixins/[name]` and called `[name].yaml`. For example, _site/mixins/address/address.yaml_.

.address.yaml
[source,yaml]
----
kind: "Mixin"
title: "Full address"
form:
  - type: "TextLine"
    name: "addressLine"
    label: "Street address"
    occurrences:
      min: 0
      max: 2
  - type: "TextLine"
    name: "city"
    label: "City"
    occurrences:
      min: 1
      max: 1
  - type: "TextLine"
    name: "zipCode"
    label: "Zip code"
    occurrences:
      min: 1
      max: 1
  - type: "TextLine"
    name: "country"
    label: "Country"
    occurrences:
      min: 1
      max: 1
----

== CMS.yaml

To activate a mixin for your project or site, it must be referenced in the application's CMS descriptor. The example below adds the `address` mixin to all content within its scope.

.cms.yaml
[source,yaml]
----
kind: "CMS"
mixins:
  - name: "address"
form: []
----

=== Options

It's possible to restrict a mixin for specific content types using regular expressions. This is especially convenient when you apply a mixin to all content types via the CMS descriptor but want to exclude some content types.

Use regular expressions in the `allowContentTypes` attribute to enable or disable it for specific content type(s).
By default a mixin will be added to content items of all types with no option to remove it, but you can make it optional by setting `optional` to _true_. Optional mixins have to be manually enabled inside Content Wizard to be added to the content data.

If `allowContentTypes` and `optional` are not set, the mixin will automatically be enabled for all content types. See <<schemas/form-items/contentselector#allowContentType, modes>> of content type filtering.

[source,yaml]
----
kind: "CMS"
mixins:
  - name: "my-mixin-1" # <1>
  - name: "my-mixin-2" # <2>
    allowContentTypes: "^(?!base:folder$).*"
  - name: "my-mixin-3" # <3>
    allowContentTypes: "portal:site"
    optional: true
form: []
----

<1> `my-mixin-1` will automatically be enabled for all content types, with no option to disable it in the Content Studio.

<2> `my-mixin-2` will be added for all content types with no option to remove it in the Content Studio, except for content type `base:folder` for which it will not be shown at all.

<3> `my-mixin-3` optionally enabled for built-in content type `portal:site`


== Output

Mixin content is stored in the content under the key `x` (short for miXin). 

To avoid conflict between mixins from different namespaces, the namespace is used as a prefix. For example, if you have the namespace `com.company`, with a mixin called `address` containing a field `city`, the value of that field will be stored and searchable `x.com-company.address.city`.

The JSON structure of the mixin content will look like this:

[source,JSON]
----
{
  "x": {
    "com-company": {
        "address": {
            "city": "Oslo"
        }
    }
  }
}
----

NOTE: Namespaces are transformed by replacing dots with dashes. So `com.company` becomes `com-company`. This is done to ensure that the keys are valid for content querying.

== GraphQL

When querying content with mixins via the GraphQL API, the mixin fields are available under the `x` field. For example, to query the JSON structure shown above, you would use the following GraphQL query:

[source,GraphQL]
----
{
  guillotine {
    query(key: "contentid") {
      x {
      	com_company {
          address {
          	city
          }
        }
      }
    }
  }
}
----

NOTE: Due to GraphQL field naming restrictions (`-` and `.` are not allowed), dots are replaced with underscores. So `com.company` becomes `com_company`.