= Schema system
imagesdir: images
:toc: right

Schemas are the heart of the CMS, enabling you to express your content model as code.

== Introduction

Schemas are used to define various editorial elements within the CMS, such as <<content-types#, Content Types>> and <<mixins#, Mixins>>. Schemas may contain a <<form#, Form>> which allow you to declare advanced data structures within your content.

== Installation and usage

Schemas are deployed to Enonic XP via Enonic apps. When an application gets installed, the schemas are registered in the system, and instantly reflected in Content Studio and related APIs. 

Visit the https://developer.enonic.com/docs/dev[Enonic App development docs] for more information on how to create and deploy Enonic apps.


== Definition

Schemas are defined using YAML files. A schema definition commonly contains the following elements:

* Namespace and name (i.e. "com.example:article")
* <<#kinds, Kind>> (i.e. "content-type", "mixin")
* Configuration (Validated fields for each schema kind)
* <<form#, Form>> (Optionally defines a form, and hence the data structure of the content)
* Attributes (User-defined non-validated fields)

TODO: Example descriptor

[[kinds]]
== Schema kinds
Enonic currently support the following content schemas kinds. Each kind has a specific role in the CMS, and may have specific configuration options.

=== Reuse
* <<schemas/form-fragments#, Form Fragments>>
* <<mixins#, Mixins>>

=== Content types

* <<content/content-types#, Content Types>>
* <<media/media-types#, Media Types>>

=== Rich Text

* <<richtext/macros#, Macros>>
* <<richtext/styles#, Styles>>

=== Page domain

* <<pages#, Pages>>
* <<pages/parts#, Parts and Layouts>>


== Schema localization

You may provide <<i18n#, translations>> for your schemas in multiple languages for better usability. 


