= Schemas and namespaces
imagesdir: images
:toc: right

Schemas are the heart of the CMS, enabling you to express your content model as code.

== Introduction

Schemas are used to express editorial elements within the CMS, such as content type. Schemas optionally contain a form which allow you to express advanced data structures. Once deployed to Enonic XP, schemas are used by Content Studio to generate user interfaces, and by the APIs. Schemas are organized in namespaces to prevent naming conflicts and promote reuse. 

== Ingredients of a schema

A schema is made up of a few key ingredients:

* Namespace and name (i.e. "com.example:article")
* Kind (i.e. "content-type", "mixin" etc)
* Configuration (Specific to each schema kind)
* <<form#, Form>> (Optionally defines a form, and hence the data structure of the content)
* Indexing rules (optionally defines indexing rules for the form inputs)

Content Studio is available in multiple languages, and you may also <<i18n#, translate>> your schemas in multiple languages, for better usability. 


== Usage

TODO - YAML example.

== Schema kinds
TODO: Link to each kind

Enonic implements the following content schemas

* content-type
* mixin
* page
* part
* layout
* form-fragments


== Other use-cases

In Enonic XP, the schema concept is also used in other contexts than the CMS. For instance, identity providers and tasks also use schemas to define their configuration. In these cases, only a generic subset of the form imputs are supported, and the form output will not be persisted as content, but rather stored in the identity provider or task definition.
