= Schema system
imagesdir: images
:toc: right

Schemas are the heart of the CMS, enabling you to express your content model as code.

== Introduction

Schemas are used to define various editorial elements within the CMS. Schemas may contain a <<form#, Form>> which allow you to declare custom data structures.

The available schema kinds are:

* <<content/content-types#, Content Types>>
* <<content/mixins#, Mixins>>
* <<schemas/form-fragments#, Form Fragments>>
* <<pages#, Pages, Parts and Layouts>>
* <<richtext/macros#, Macros>>
* <<richtext/styles#, Styles>> 

== Schema deployment

Schemas are managed as code, and deployed to Enonic XP via Enonic apps. When an application gets installed, the schemas are registered in the system, and instantly reflected in Content Studio and related APIs. 

Visit the https://developer.enonic.com/docs/code[Enonic Development Kit] documentation for more information.


== Descriptor

Schemas are defined using YAML files, and registered with a unique identifier <namespace>:<name> (i.e. "com.example:article")

.Sample schema definition
[source,yaml]
----
kind: “ContentType”  # <1>
title: “Person”  # <2>
displayNameLabel: “Full Name”  # <3>
form: []  # <4>
----

<1> <<#kinds, Kind>> - i.e. "ContentType", "Mixin" etc.
<2> Title - Human readable schema name.
<3> <<#configuration, Configuration>> - Validated fields for each schema kind
<4> <<form#, Form>> - Optional form that declares a custom data structure for the schema.


== Schema localization

You may provide <<i18n#, translations>> for your schemas in multiple languages for better usability in Content Studio. 


