= Base content types
The fundamental content types built into Enonic XP, which all other content types build upon.

== Introduction

To enable the creation of content items, Enonic XP ships with a set of built-in content types. These are the base content types that all other content types build upon. They are all located in the `base` namespace. The base content types are divided into two categories: abstract and concrete. The abstract base types are meant to be extended when creating custom content types, while the concrete base types are ready to be used as they are.

TODO: Verify
Common for all base content types is that they are all subtypes of the root content type `base:content`, which is the most basic content type in Enonic XP. The `base:content` type is abstract and cannot be used directly to create content items, but it provides a common set of properties and capabilities that all content types inherit.

== Abstract base types

Enonic XP ships with a set of abstract types that every other content type builds upon. They are all located in the `base` namespace. The base types are:

=== Structured (base:structured)

The structured base type supports <<../forms#, form definitions>>, and is as such the common foundation for <<custom#, custom content types>>.

is-abstract:: true
is-final:: false
allow-child-content:: true

=== Media (base:media)
[[media]]

Abstract type for files uploaded to the CMS. Files will automatically be detected and assigned a pre-defined content type, also known as <<media# Media Types>>.

is-abstract:: true
is-final:: false
allow-child-content:: false


== Concrete base types

Additionally, Enonic XP also ships with a set of concrete base types that are ready to be used as they are. They are all located in the `base` namespace. The concrete base types are:

=== Shortcut (base:shortcut)
Used for referencing or redirecting to another content item in the structure.
Optional name-value parameters can be set to be added to the redirect URL.

is-abstract:: false
is-final:: true
allow-child-content:: true

=== Folder (base:folder)
Folders are simply containers for child content, with no other properties than their name and Display Name. They are helpful in organizing your content.

is-abstract:: false
is-final:: false
allow-child-content:: true

=== Unstructured (base:unstructured)

The unstructured content type is a special content type that permits the creation of any property or structure without actually defining it first. It can only be used via API.

This is convenient for storing content, when the properties and their types vary from instance to instance - and the item needs to be editorially managed and published. For most such scenarios, developers should consider using the <<../storage#, low-level storage>> instead.

Since the content data is unstructured (basically schemaless), there is currently no default user interface (i.e. in Content Studio) that facilitates editing of the unstructured content.

is-abstract:: false
is-final:: true
allow-child-content:: true

