= Custom content types
By defining your own content types, you can create a content model that is perfectly tailored to your needs.

== Introduction

Custom content types are defined with schemas, and can be used in the same way as built-in content types. You can create as many custom content types as you need, and organize them in your own namespaces for better reuse and organization.

== Usage

Custom content types are defined in YAML, and must be placed in the `site/content-types` directory of your app. The content type definition must be placed in a subdirectory matching the content type name, and the file name must match the content type name as well. For example, a content type with the name `com.example:article` must be defined in `site/content-types/article/article.yaml`. You may only have one content type per directory, but you can of course have as many directories as you like.

== SuperType

TODO: Verify

The supertype attribute of a content type defines the handling of the content type. For most cases, it should be set to `base:structured`, which is a very flexible supertype which among other things support the definition of <<../forms#>>, and hence structured content.

NOTE: You may not specify a custom content type as a supertype, nor may you create circular dependencies between content types. This is to ensure that the form mechanics are consistent and predictable, and to avoid potential issues with circular dependencies between content types.

== Icon
A content type may optionally have its own specific icon which is used to represent the content type in Content Studio. The icon can be assigned to the content type by adding a PNG or SVG file with the same name in the content type directory: `my-content-type.svg`