= Portal content types
The portal content types are a set of pre-defined content types that are used for building websites in Enonic XP

== Introduction

Portal types are are located in the `portal` namespace, and are all subtypes of the abstract type `base:structured`. Portal types go hand in hand with the <<components#, Page Component schemas>>. The portal content types are:

=== Site (portal:site)

Site content items serves the purpose of acting as website root entries. It enables selecting and configuring applications for a website. Content types, components, filters, x-data and more from the applications selected will be available for use inside the site content tree.

NOTE: Application-specific content types may only be used within a site, to which the application has been added.

super-type:: base:structured
is-abstract:: false
is-final:: true
allow-child-content:: true

=== Page Template (portal:page-template)
Instead of always having to configure the page controller for each content, page templates provide a default setup for how a content type is displayed on a site.

super-type:: base:structured
is-abstract:: false
is-final:: true
allow-child-content:: true

=== Template folder (portal:template-folder)

This is a special content type. Every site automatically creates a child content of this type named _templates. The templates folder holds all the page templates of that site. It may not hold any other content type, and it may not be created manually in any other location.

super-type:: base:folder
is-abstract:: false
is-final:: true
allow-child-content:: portal:page-template

=== Fragment (portal:fragment)

The Fragment content type represents a reusable page component. A content of this type contains a page component(Part, Layout, Text, Image) that can be re-used in other pages. But it only needs to be maintained in one place.

super-type:: base:structured
is-abstract:: false
is-final:: true
allow-child-content:: true

To create a content of type `portal:fragment` edit an existing page with Page Editor, select the context menu of an existing component in the page, and then clicking on “Create Fragment”. Once created, the fragment content can be referenced in other pages by inserting a Fragment component in the page.

A Fragment content can be edited with Page Editor and the changes applied to the component will immediately be available in the pages that include the fragment. When a page containing fragment a component is rendered, the components of the portal:fragment content pointed by the fragment component are rendered in the place of the fragment component.

There is a default page for rendering and edit fragments. The default page does not have any styles defined, but it is possible to render it with the application theme and styles by defining a controller <<../framework/mappings.adoc#,mapping>> with `<match>type:'portal:fragment'</match>`
